version: '3.9'

services:
  api:
    build: .
    depends_on:
      - database
    ports: 
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_HOSTNAME=database
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=<your_password>
      - DATABASE_NAME=<your_db_name>
      - DATABASE_USERNAME=<your_username>
      - SECRET_KEY=<your_secret_key>
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=<your_expire_minutes>

  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=<your_password>
      - POSTGRES_DB=<your_db_name>
    volumes:
      - postgres-db:/var/lib/postgresql
    ports:
      - 5432:5432

volumes:
  postgres-db: