name: Build and Deploy code

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Init workflow
        run: echo 'ðŸš€ Initialazing CI/CD pipeline workflow to sync FastAPI application changes'
      - name: Pulling git repository
        uses: actions/checkout@v2
      - name: Install python version 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install all the dependencies
        run: pip install -r requirements.txt
      - name: Run all test with Pytest
        run: |
          pip install pytest
          pytest -s -v